### ISSUE TITLE
Duplicated message when domain is added

### ISSUE THREAD

**Issue by vlikhtanskiy** [plesk/ext-domain-connect#42]
Now there are 2 messages:
1. From Plesk: The domain %%domain%% does not resolve or resolves to another IP address (%%ip%%). Please correct DNS settings.
2. Message from DomainConnect extension

We need to hide first one. For example using JS.

**Comment by xgin** [comment]
After the changes in https://github.com/plesk/ext-domain-connect/pull/70 the message is not considered as a duplicate: it is green and more positive :)
